FIND_PATH(
        SDL2_TTF_INCLUDE_DIR SDL_ttf.h
        PATH_SUFFIXES
        include/SDL2_ttf SDL2_ttf)

FIND_LIBRARY(SDL2_TTF_LIBRARY NAMES SDL2_ttf)

IF (SDL2_TTF_INCLUDE_DIR AND SDL2_TTF_LIBRARY)
    SET(SDL2_TTF_FOUND TRUE)
ENDIF (SDL2_TTF_INCLUDE_DIR AND SDL2_TTF_LIBRARY)


IF (SDL2_TTF_FOUND)
    MESSAGE(STATUS "Found SDL2_TTF : include : ${SDL2_INCLUDE_DIR} library : ${SDL2_TTF_LIBRARY}")
ELSE (SDL2_TTF_FOUND)
    MESSAGE(FATAL_ERROR "Could not find SDL2_ttf library. include : ${SDL2_INCLUDE_DIR} library : ${SDL2_TTF_LIBRARY}")
ENDIF (SDL2_TTF_FOUND)
