FIND_PATH(
        SDL2_IMAGE_INCLUDE_DIR 
            SDL_image.h
        PATH_SUFFIXES
            include/SDL2_image SDL2_image)

FIND_LIBRARY(SDL2_IMAGE_LIBRARY NAMES SDL2_image)

IF (SDL2_IMAGE_INCLUDE_DIR AND SDL2_IMAGE_LIBRARY)
    SET(SDL2_IMAGE_FOUND TRUE)
ENDIF (SDL2_IMAGE_INCLUDE_DIR AND SDL2_IMAGE_LIBRARY)


IF (SDL2_IMAGE_FOUND)
    MESSAGE(STATUS "Found SDL2_TTF : include : ${SDL2_INCLUDE_DIR} library : ${SDL2_IMAGE_LIBRARY}")
ELSE (SDL2_IMAGE_FOUND)
    MESSAGE(FATAL_ERROR "Could not find SDL2_ttf library. include : ${SDL2_INCLUDE_DIR} library : ${SDL2_IMAGE_LIBRARY}")
ENDIF (SDL2_IMAGE_FOUND)
