FIND_PATH(
    SDL2_INCLUDE_DIR SDL.h
    PATH_SUFFIXES
        include/SDL2 SDL2)

FIND_LIBRARY(SDL2_LIBRARY NAMES SDL2)
FIND_LIBRARY(SDL2MAIN_LIBRARY NAMES SDL2main)

IF (SDL2_INCLUDE_DIR AND SDL2_LIBRARY)
	SET(SDL2_FOUND TRUE)
ENDIF (SDL2_INCLUDE_DIR AND SDL2_LIBRARY)


IF (SDL2_FOUND)
	MESSAGE(STATUS "Found SDL2 : include : ${SDL2_INCLUDE_DIR} library : ${SDL2_LIBRARY}")
ELSE (SDL2_FOUND)
	MESSAGE(FATAL_ERROR "Could not find SDL2 library. include : ${SDL2_INCLUDE_DIR} library : ${SDL2_LIBRARY}")
ENDIF (SDL2_FOUND)

